version: "3.9"

services:
  one_api:
    build:
      context: "../../../Hitaya_oneAPI"
      dockerfile: "docker/oneApi/Dockerfile"
    volumes:
      - ../../../Hitaya_oneAPI:/ml_app
    ports:
      - "5000:5000"
    container_name: one_api

