apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2023-05-29T20:53:07Z"
    generation: 1
    name: my-flask-app
    namespace: default
    resourceVersion: "48443"
    uid: 2b2e9d05-0c95-447f-8449-0de704d07768
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: my-flask-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: my-flask-app
      spec:
        containers:
        - image: 514717732227.dkr.ecr.ap-south-1.amazonaws.com/oneapi_one_api:1.0.0
          imagePullPolicy: IfNotPresent
          name: my-flask-container
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-05-29T20:56:29Z"
      lastUpdateTime: "2023-05-29T20:56:29Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-05-29T20:53:07Z"
      lastUpdateTime: "2023-05-29T20:56:29Z"
      message: ReplicaSet "my-flask-app-6cd977b975" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
